sbitx.c, sbitx_gtk.c
EQ menu is hidden until the volume encoder is long-pressed for 1 second.  also fixed the waterfall crash that JJ already fixed..I must have made it mad again,
=> gtk enhancements and kbd crash fix

para_eq.h, sbitx.c, sbitx_gtk.c
The enable/bypass only cycles when the tx/rx is cycled.  Planning on adding the check to the main loop in sbitx.c to get it to respond as it is toggled.  But for now.. this is good.
=> updated eq functions added enable/bypass

sbitx.c, sbitx_gtk.c, sound.h
this should take the r1:volume setting and logarithmically adapt it to the TX Master mixer rx_value. this will give a more controllable AF volume control
=> volume control normalization update

build
Build an optimized binary with additional command line argument 'o'.  Otherwise acts the same way as previous iterations.
=> Update build script

src/fft_filter.c
re-enabled the filter details as well as updated the path to wisdom files
=> corrected path and printf

src/hamlib.c, src/sbitx_gtk.c, src/sdr.h
- Honor mode change bw requests
- Added long version of commands
=> Minor hamlib additions

src/sbitx_gtk.c
=> Fix some dupes

src/modem_cw.c
=> Fix IambicB sequence

src/sdr_ui.h
=> reversion dev branch

src/sbitx_gtk.c
Added a toggle option for full-screen or normal spectrum/waterfall visualization in voice modes. 
Adjusted default low band pass from 300hz to 100hz in preparation for WWV tools
Cleaned up some issues with malformatted comments I had left in the past.
=> added fullscreen spectrum/waterfall option

src/modem_ft8.c, src/modems.c, src/sbitx.c, src/sbitx_gtk.c, src/sdr.h
- Tuning can be done within fldigi now without have to use rig's pitch feature
- Pitch removed altogether from DIGI mode
=> Fix for inability to adjust pitch from fldigi

src/modem_ft8.c, src/modems.c, src/sbitx.c, src/sbitx_gtk.c, src/sdr.h
* Hopeful fix for fldigi pitch issue
* Remove pitch related stuff from DIGI mode
* Handle DIGI mode
* Clean up
=> Fix for inability to adjust pitch from fldigi (#50)

src/sbitx.c, src/sbitx_gtk.c, src/sdr.h
I added a VFO indicator so that the OM would realize that the lock is on at a glance.
=> Vfo lock indicator addition

src/sbitx.c
Add TCXO Calibration Option to the hw_settings,ini file
tcxo=25000000
Reference: https://github.com/drexjj/sbitx-ham-apps/wiki/TCXO-Calibration
=> Add TCXO Calibration Option

data/create_db.sql, data/default_hw_settings.ini, data/default_hw_settings_V3.ini, data/default_hw_settings_v2.ini, data/default_settings.ini, src/sbitx.c
- Added 60m to default user settings in prep for 60m addition
- Changed default hardware settings files to include TCXO calibration and 60m definitions
=> Drexjj fixes

.gitignore, build, renice.sh, src/hamlib.c, src/sbitx_gtk.c, src/webserver.c
- Remove web server path debug output
- Updated build script (and gitignore for files gcc may create for PGO)
- Added a renice script to change priority of sbitx app
=> Few small fixes additions

.gitignore, src/docs/commands.txt, src/sbitx_gtk.c
- the \macro list command appears to not have been completed; fixed
- Updated docs
- Updated gitignore to ignore custom macros
=> GTK \macro list command

release_notes.txt, src/docs/commands.txt, src/eq_ui.c, src/eq_ui.h, src/para_eq.c, src/para_eq.h, src/sbitx.c, src/sbitx_gtk.c, src/sound.h
=> Revert "dev sync to 60meters"

data/default_hw_settings.ini, data/default_hw_settings_V3.ini, data/default_hw_settings_v2.ini, data/default_settings.ini, release_notes.txt, src/docs/commands.txt, src/eq_ui.c, src/eq_ui.h, src/para_eq.c, src/para_eq.h, src/sbitx.c, src/sbitx_gtk.c, src/sound.h
Add functionality for 60 meters
Move SET button to menu and move web button over for 60 meter band
Requires an addition to hw_settings.ini
[tx_band]
f_start=5250000
f_stop=5450000
scale=0.004
Already added this to the default hw settings files
=> 60 meter additions

src/sbitx_gtk.c
the update makes the panadapter more pleasant to look at by improving the refresh rate in SSB
=> adjusted default ticks to improve panadapter visualization pleasure

src/logbook.c
Fixes the cause for the sbitx crash that occurred when a new contact was added (e.g by FT8) and the logbook window was open.
=> log refill fix

src/hamlib.c
=> Hamlib fixes

src/sbitx.c, src/sdr_ui.h
Reverts drexjj/sbitx#92
Still have issues at high power with the audio chain
=> Revert "Patch v4.02 DE LPF Relay and Volume Fix"

README.md, src/sbitx.c, src/sbitx_gtk.c, src/sdr_ui.h, web/index.html, web/style.css
Added a graphical character, bandstack position indicator beneath the selected band.
Eg -=-- meaning 2. stack position.
This option is off by default, but can be set to ON by the user with **\BSTACKPOSOPT ON**
=> Band stack pos option

src/sbitx.c, src/sdr_ui.h
* Patch v4.11
* Fixed 20 msec delay  statement for qro function
---------
=> QRO Delay Patch v4.11 (#98)

src/para_eq.c
Added smoothing across bands to suppress nasty artifacts affecting sound quality.
=> Updated para_eq.  

src/sbitx.c, src/sbitx_gtk.c, src/sdr.h, src/sdr_ui.h
Improved Waterfall controls. fixed waterfall values not loading at start, add limiter after RX eq to prevent clipping. Included are improved (IMO, subjective) DSP and ANR mods. However these mods are commented out. Feel free to test them.
=> Merge in RX eq and other updates

src/sbitx_gtk.c
=> Updated menu layout

release_notes.txt, src/eq_ui.c, src/eq_ui.h, src/hamlib.c, src/hamlib.h, src/para_eq.c, src/para_eq.h, src/sbitx.c, src/sbitx_gtk.c, src/sdr.h, src/sdr_ui.h
=> Revert "merge changes for rx-eq-wf"

src/sbitx_gtk.c, web/index.html
=> merge changes 

src/sbitx_gtk.c, src/sdr_ui.h
=> Patch for Tune toggle

src/sbitx_gtk.c
Varying the IF value makes the spectrum fall below zero or up to the top of the graph. E.g. setting it to the value that makes the S-meter correct hence gives a bad spectrum graph.
This PR makes the spectrum always showing the current spectrum, diligently based on the bottom of its graph window.
=> Automatically adjust the spectrum baseline to the bottom of the graph

src/sbitx.c
This PR contains a cleanup of the power max-hold calculation
Bonus: sanitization of SWR calculation in limit cases (but no max-hold [yet?] for the SWR)
=> Power max-hold readable visualization cleanup. Sanitize swr calculation

src/sbitx.c
Also sanitize the swr calculation in the case of little or no vfwd
=> Power max-hold readable visualization. (#182)

src/sbitx.c
Power max-hold readable visualization.
Also sanitize the swr calculation in the case of little or no vfwd.
by ffurano
=> Power max-hold readable visualization. (#182) (#184)

src/hamlib.c, src/hamlib.h
=> Updated Hamlib with turned off AUDIO_TCP and fix for mode.

src/sbitx_gtk.c
A new toggle button in menu2 enables the auto-adjustment of the spectrum and waterfall baselines, in order to
correctly show the signal that is being received independently from the IF gain setting.
=> Add menu option to automatically adjust the spectrum and waterfall baseline

src/sbitx_gtk.c
=> Automatically adjust the spectrum and waterfall baseline. With on/off button

src/sbitx.c, src/sbitx_gtk.c, src/sdr.h, src/webserver.c, web/index.html
merging branches together to consolidate efforts to one branch
=> merge 0beat and BFO enhancements into merge test 

src/sbitx.c, src/sbitx_gtk.c
This should update the wftx branch with the latest push from the jb-wftx branch.. (not the easiest to do from a phone, hihi. )
=> Jb wftx to wftx-web

release_notes.txt, src/sdr_ui.h, web/index.html, web/logbook.html
=> Revert "v5.01"

src/sbitx_gtk.c
- focus returns to volume control (aka multi function knob) after 15 seconds inactivity
=> Implement MFK volume control focus control

src/modem_cw.c
reviewer (Gyula) noted missing Prosigns
=> add <SK> and <BK> prosigns
